Update passwdupdate

diff --git a/passwdupdate b/passwdupdate
--- a/passwdupdate
+++ b/passwdupdate
@@ -1,22 +1,55 @@
 #!/bin/sh
 #⭐️#
 echo "----------------------------------------------------------------------"
-echo "请更新系统密码"
+echo "请更新系统管理密码"
 echo "Please update the system password"
 echo "----------------------------------------------------------------------"
-#sleep 2
+sleep 2
+
+# 禁用回显
+stty -echo
 
 # 提示用户输入新密码
-echo -n "Enter new password: "
-read -s new_password
+echo -n "输入新密码 Enter new password: "
+read new_password
 echo
+
+# 再次提示用户输入新密码进行确认
+echo -n "输入新密码进行确认 Confirm new password: "
+read confirm_password
+echo
+
+# 启用回显
+stty echo
+
+# 检查两次密码输入是否一致
+if [ "$new_password" != "$confirm_password" ]; then
+  echo "检查到两次密码输入不一致，请重试！ Password confirmation failed. Please try again."
+  exit 1
+fi
 
 # 使用chpasswd命令更新密码
 echo "root:$new_password" | chpasswd
 
 # 检查密码更新是否成功
 if [ $? -eq 0 ]; then
-  echo "Password updated successfully."
+  echo "密码更新成功！ Password updated successfully."
 else
-  echo "Failed to update password."
+  echo "密码更新失败！请重试！Failed to update password."
+  exit 1
 fi
+
+# 验证密码是否成功修改
+stty -echo
+echo -n "输入您刚才更新的密码，验证密码是否成功修改。Enter the new password to verify: "
+read verify_password
+stty echo
+echo
+
+# 比较输入的密码和更新后的密码是否匹配
+if [ "$verify_password" = "$new_password" ]; then
+  echo "密码验证成功！ Password verification successful."
+else
+  echo "密码验证失败！请重新更新修改密码！ Password verification failed. Please try again."
+fi
+#⭐️#
