Update Update

diff --git a/Update b/Update
--- a/Update
+++ b/Update
@@ -1,11 +1,40 @@
 #!/bin/bash
 # 之前被Windows编辑符号^M搞死！！！
 # wget -qO- https://git.io/VPS.sh | bash
-#⭐️#
 echo "----------------------------------------------------------------------"
 echo "请更新系统密码"
 sleep 2
-passwd
+echo "----------------------------------------------------------------------"
+# 提示用户输入新密码
+read -s -p "Enter new password: " new_password
+echo
+
+# 提示用户再次输入新密码进行确认
+read -s -p "Confirm new password: " confirm_password
+echo
+
+# 检查两次输入的密码是否一致
+if [ "$new_password" != "$confirm_password" ]; then
+  echo "Passwords do not match. Please try again."
+  exit 1
+fi
+
+# 根据不同的发行版选择对应的命令更新密码
+if [ -x "$(command -v passwd)" ]; then
+  # Ubuntu
+  echo "root:$new_password" | passwd --stdin root
+else
+  # CentOS
+  echo "root:$new_password" | chpasswd
+fi
+
+# 检查密码更新是否成功
+if [ $? -eq 0 ]; then
+  echo "Password updated successfully."
+else
+  echo "Failed to update password."
+fi
+#⭐️#
 echo "----------------------------------------------------------------------"
 echo "Set up IPV6 DNS resolution IPv4 DomainName"
 sleep 2
